### ISSUE TITLE
Quest: Wellness

### ISSUE THREAD

**Issue by jonpitch** [b-lab-org/ember-cli-impact-core#123]
## Overview
This is a general bucket of technical debt, developer ergonomics, UI improvements, etc.

## Tasks
- [ ] module unification
Ember is moving toward a pod-like file system in the near future. This would group common files by feature rather than having to look in numerous places by naming convention. Assuming this is what the team wants to do, there's a [codemod](https://github.com/rwjblue/ember-module-migrator) to do so. It's backward compatible with "classic" apps and addons.

- [ ] test unification
Ember is looking to consolidate the syntax of writing acceptance tests and integration tests. To do so, they're recommending moving toward [@ember/test-helpers](https://github.com/emberjs/ember-test-helpers) (there's a [codemod](https://github.com/simonihmig/ember-test-helpers-codemod) here).

- [ ] remove unused translations
We do our best to remove translations when they are no longer required, but chances are our applications have several unused translations that are just adding bloat to our payload. Some sort of test or AST transform would be helpful to detect a translation that exists in a `.json` file but not used in a template or component.

- [ ] `async-button` component
We do a `{{#if loading}} show loader {{else}} show button {{/if}}` pattern everywhere. I'd like to consolidate this into a component.

- [ ] [ember-cli-addon-docs](https://github.com/ember-learn/ember-cli-addon-docs)
It would be nice to remove our custom docs site and migrate toward this addon, which I anticipate the rest of the Ember addon community adopts over time. It would reduce our manual maintenance of documentation as well as provide more documentation.
